version: '2'
    
services:
  app:
    build: .
    depends_on: 
      - pg
      - redis
    links:
      - pg
      - redis
    command: 'bash -c go-compose'
    environment:
      PORT: 5000
      REDIS_URL: 'redis://redis:6379'
      DATABASE_URL: 'postgres://postgres:postgres@pg:5432?sslmode=disable'
      PROD: 'false'
    ports:
      - '5000:5000'
  redis:
    container_name: redis
    image: redis:latest
    expose:
      - '6379'
  pg:
    image: postgres:latest
    container_name: postgres
    expose:
      - "5432"